name: Run Node.js Script from Private Repo

on:
#  push:
  #  branches:
  #    - main  # Trigger this action on push to the public repo's main branch
  workflow_dispatch:
jobs:
  run-script9:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v3  # This checks out the public repo

    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set your required Node.js version

    - name: Install dependencies (if any)
      run: npm install @cosmjs/proto-signing
  # Install dependencies if needed

    - name: Run Node.js script from private repo
      env:
          DELAY_MINUTES: 1
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS9 }}
      run: |
        curl https://api.ipify.org
        node check1.js
      continue-on-error: true

  run-script10:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v3  # This checks out the public repo

    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set your required Node.js version

    - name: Install dependencies (if any)
      run: npm install @cosmjs/proto-signing
  # Install dependencies if needed

    - name: Run Node.js script from private repo
      env:
          DELAY_MINUTES: 1
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS10 }}
      run: |
        curl https://api.ipify.org
        node check1.js
      continue-on-error: true

  run-script11:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v3  # This checks out the public repo

    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set your required Node.js version

    - name: Install dependencies (if any)
      run: npm install @cosmjs/proto-signing
  # Install dependencies if needed

    - name: Run Node.js script from private repo
      env:
          DELAY_MINUTES: 1
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS11 }}
      run: |
        curl https://api.ipify.org
        node check1.js
      continue-on-error: true

  run-script12:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v3  # This checks out the public repo

    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set your required Node.js version

    - name: Install dependencies (if any)
      run: npm install @cosmjs/proto-signing
  # Install dependencies if needed

    - name: Run Node.js script from private repo
      env:
          DELAY_MINUTES: 1
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS12 }}
      run: |
        curl https://api.ipify.org
        node check1.js
      continue-on-error: true

  run-script13:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v3  # This checks out the public repo

    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set your required Node.js version

    - name: Install dependencies (if any)
      run: npm install @cosmjs/proto-signing
  # Install dependencies if needed

    - name: Run Node.js script from private repo
      env:
          DELAY_MINUTES: 1
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS13 }}
      run: |
        curl https://api.ipify.org
        node check1.js
      continue-on-error: true

  run-script14:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v3  # This checks out the public repo

    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set your required Node.js version

    - name: Install dependencies (if any)
      run: npm install @cosmjs/proto-signing
  # Install dependencies if needed

    - name: Run Node.js script from private repo
      env:
          DELAY_MINUTES: 1
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS14 }}
      run: |
        curl https://api.ipify.org
        node check1.js
      continue-on-error: true

  run-script15:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v3  # This checks out the public repo

    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set your required Node.js version

    - name: Install dependencies (if any)
      run: npm install @cosmjs/proto-signing
  # Install dependencies if needed

    - name: Run Node.js script from private repo
      env:
          DELAY_MINUTES: 1
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS15 }}
      run: |
        curl https://api.ipify.org
        node check1.js
      continue-on-error: true

  run-script16:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v3  # This checks out the public repo

    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set your required Node.js version

    - name: Install dependencies (if any)
      run: npm install @cosmjs/proto-signing
  # Install dependencies if needed

    - name: Run Node.js script from private repo
      env:
          DELAY_MINUTES: 1
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS16 }}
      run: |
        curl https://api.ipify.org
        node check1.js
      continue-on-error: true
